name: stroll_t1
description: "Task 1 for Stroll"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod:
  riverpod_annotation:
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator:
  build_runner:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Proxima_Nova
      fonts:
        - asset: fonts/Proxima_Nova_Thin.otf
          weight: 300
          style: normal
        - asset: fonts/Proxima_Nova_Thin_Italic.otf
          weight: 300
          style: italic
        - asset: fonts/Proxima_Nova_Regular.otf
          weight: 400
          style: normal
        - asset: fonts/Proxima_Nova_Semibold.otf
          weight: 600
          style: normal
        - asset: fonts/Proxima_Nova_Semibold_Italic.otf
          weight: 600
          style: italic
        - asset: fonts/Proxima_Nova_Bold.otf
          weight: 700
          style: normal
        - asset: fonts/Proxima_Nova_Bold_Italic.otf
          weight: 700
          style: italic
